spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/ventas?serverTimezone=GMT-5
    #Desarrollo
    url: jdbc:mariadb://sistemariego.cggyseqn25u8.us-east-2.rds.amazonaws.com:3306/DBSistemaRiego?serverTimezone=GMT-5
    #Producci√≥n
    #url: jdbc:mariadb://stockydb.cggyseqn2du8.us-east-2.rds.amazonaws.com:3306/dbOdontomedi?serverTimezone=GMT-5
    username: usuario
    password: password
    driverClassName: org.mariadb.jdbc.Driver
mybatis:
  type-aliases-package: com.example.myproject.mapper
  mapper-locations: mybatis/mapper/**/*.xml